Telmate/terraform-provider-proxmox

proxmox/preprovision.go

The returned error is now already formatted. Closes #9

The remote API was changed, adapt code

---

proxmox/resource_vm_qemu.go

The agent value from the api is received as an integer instead of an string. Therefore applying terraform changes fails when the agent was active within the base image.
Fixes https://github.com/Telmate/terraform-provider-proxmox/issues/46

Changed agent type to mirror the type from the proxmox api

---

examples/cloudinit_example.tf

There is no assignment necessary for the typeset, see the example in [Terraform Docs -  Schema Attributes and Types - TypeSet](https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset)

Cloudinit Example: Fix Typeset Assignment

---

README.md
examples/cloudinit_example.tf
proxmox/resource_vm_qemu.go

This allows to set the resource pool for a new VM. Without this change, the VM creation will fail for non-root users. With this change, the VM can be created in a particular resource group (supports creation by iso image or as clone from an existing template). The example and Readme file are amended accordingly.
This change depends on https://github.com/Telmate/proxmox-api-go/pull/38

Support setting pool for new VMs and clones (cloud-init)

---

README.md
examples/cloudinit_example.tf
examples/lxc_example.tf
proxmox/provider.go
proxmox/provisioner.go
proxmox/resource_vm_qemu.go

Sorry there was a mistake in my previous PR. If the OTP 2FA is activated the client gets a timeout.
I have added the environment var PM_OTP to connect using the 2FA.

Allow to connect using OTP 2FA

---

README.md
examples/cloudinit_example.tf
proxmox/resource_vm_qemu.go

The new var **scsihw** allows to set an other SCSI Controller model using the Proxmox API

Add SCSI controller support

---

proxmox/resource_vm_qemu.go

Cloud init is returning a disk size in MB and the function diskSizeGB was not able to convert it in GB so the new disk size was not the wanted one.
I have also added support for other units, will be useful for the future.

Fix Cloud-init resizing

---

proxmox/resource_lxc.go

This changes the type of the gw fields to a string instead of a boolean, see PVE API:
```
name=<string> [,bridge=<bridge>] [,firewall=<1|0>] [,gw=<GatewayIPv4>] [,gw6=<GatewayIPv6>] [,hwaddr=<XX:XX:XX:XX:XX:XX>] [,ip=<(IPv4/CIDR|dhcp|manual)>] [,ip6=<(IPv6/CIDR|auto|dhcp|manual)>] [,mtu=<integer>] [,rate=<mbps>] [,tag=<integer>] [,trunks=<vlanid[;vlanid...]>] [,type=<veth>]
```

Change net.gw to string

---

proxmox/resource_lxc.go

This fixes the following error, when trying to create an lxc container without any features (as non-root user):
```
2019-10-03T06:11:28.596+0200 [DEBUG] plugin.terraform-provider-proxmox: 	/home/andi/gocode/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_lxc.go:522 +0x5e9
```
Terraform example:
```
resource "proxmox_lxc" "lxc-test" {
hostname = "tf1"
network {
id = 0
name = "eth0"
bridge = "vmbr0"
ip = "dhcp"
ip6 = "dhcp"
}
ostemplate = "shared:vztmpl/centos-7-default_20171212_amd64.tar.xz"
password = "rootroot"
pool = "pool1"
storage = "local-lvm"
target_node = "node1"
}

Check feature list length

---

examples/lxc_example.tf
proxmox/resource_lxc.go
proxmox/util.go

It is impossible to create LXC containers with more than one network interface, because the code of the Terraform provider includes the [device id](https://github.com/Telmate/terraform-provider-proxmox/blob/master/examples/lxc_example.tf#L15) in the request to the [PVE API](https://pve.proxmox.com/pve-docs/api-viewer/). The API, however, does not accept such a parameter (`id`).
This change fixes that issue, such that containers with multiple network devices can be created.
This change removes the device ids as discussed in #98.
The question remains, why ids for devices (network, disk, etc) need to be specified by Terraform users in the first place. Since I relied on [`DevicesSetToMap`](https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L833) to …

LXC: Remove Device IDs

---

proxmox/resource_vm_qemu.go

When the method [``UpdateConfig``](https://github.com/Telmate/proxmox-api-go/blob/dd1ec5917265ff7e35723684968818a3fce51334/proxmox/config_qemu.go#L182) fail for an http 400 response the VM is created on the cluster but the Terraform's state doesn't persist the vm id.
If we set the id and return an error terraform create the resource state but tainted this resource. 
:warning: This PR required the merge of PR [Telmate/proxmox-api-go#60](https://github.com/Telmate/proxmox-api-go/pull/60) to update the go.mod.

Set id when updateconfig fail

---

proxmox/resource_vm_qemu.go

Added clone_wait variable to configure wait time during cloning

---

go.mod
go.sum

This fixes: https://github.com/Telmate/terraform-provider-proxmox/issues/115.

Upgrade proxmox-api-go to support cephfs

---

proxmox/resource_lxc.go

Similar to #92, this changes the `hwaddr` field for the lxc resource to a string. Tested with TF 0.12.18 and PVE 5.4-13.

lxc: Change hwaddr type to string

---

README.md

After #106 there's no setup target in the makefile, and $GOPATH should be a non-issue.
Thanks for building and sharing this prototype!

Remove obsolete setup commands from readme

---

proxmox/resource_vm_qemu.go

This allows booting UEFI VMs.
This requires: https://github.com/Telmate/proxmox-api-go/pull/69.

Support setting the BIOS implementation (seabios|ovmf)

---

proxmox/resource_lxc.go

This allow to create a LXC container with a specific ID

Add a new vmID option 

---

proxmox/resource_vm_qemu.go

This PR required the PR 63 on [proxmox-api-go](https://github.com/Telmate/proxmox-api-go/pull/63).
On a previous PR #108 i set the id when I clone VM. 
But when  cloning fail on Proxmox the resource is not created.
But the method cloning method on the promox-api-go clone and configure the vm in the same method.
So i split the cloning and the configuration to set the id only if clone success.

Do not create resource when clone fail

---

proxmox/provider.go
proxmox/resource_lxc.go
proxmox/resource_vm_qemu.go

Some LXC and Qemu methods weren't properly decrementing the parallel counter and were thus causing deadlocks.
Fixes #114.

fix a deadlocking issue

---

docs/installation.md

The documentation has been updated to make it easier to run via
copy-paste. This also fixes inconsistencies between the plugin
directory used.

Fix installation steps

---

go.mod
go.sum
proxmox/provider.go
proxmox/resource_lxc.go
proxmox/resource_lxc_disk.go
proxmox/resource_vm_qemu.go
proxmox/util.go

A number of improvements to the LXC Resource.
- LXC `rootfs` property now expects a resource instead of a string.
- `mountpoints` has improved idempotency
- Added `resource_lxc_disk`
Additionally fixes some potential issues with my earlier Locking fix, #230.
Depends on changes made to `proxmox-api-go` here: https://github.com/Telmate/proxmox-api-go/pull/96

Improve LXC Resource

---

Makefile
proxmox/provider.go
proxmox/resource_vm_qemu.go
proxmox/resource_vm_qemu_test.go

This PR:
- Fixes a disk resizing bug which would error out when no resize was needed (i.e.  run a clone and no disk size change is needed)  #235 
- Adds the disk `slot` attribute that is now returned by proxmox-api-go.  Unfortunately it seems to be broken?  I can't tell if it is an issue in the provider or in the upstream proxmox-api-go, but the slot specification does not get applied in proxmox. I do not recommend using the `slot` attribute until we can figure out what's going on there.  #237 
- Clean up references to the `storage_type` attribute as that was removed from the qemu resource in the commit here:  https://github.com/Telmate/terraform-provider-proxmox/commit/aafcadd9948adc60c8f31f802fb9dc3c98cc1915
I also added additional test cases.  I did include a test case for the disk …

Add disk slot attribute, fix disk resize error on no size change, add more tests

---

proxmox/resource_vm_qemu.go

This should fix issues when importing disks with backups disabled (0 integer), because terraform will silently discard it since backup has `TypeBool` in schema.

converting disk backup value to bool

---

docs/resources/lxc.md
examples/lxc_example.tf

This fixes #250 where "storage" is stated in the wrong section in the tf-file

Remove storage argument from lxc_example.tf and documentation

---

proxmox/resource_vm_qemu.go
proxmox/resource_vm_qemu_test.go

@yukron @gentoo9ball  looks like commit 4e62f1042487a539e28e709e49fc0249278a66ba added the storage_type back to the api library but didn't include the storage_type back into the resource.    This is a quick fix to add it back in so master branch works.  Fixes #265
thanks @ameeno for raising the issue

Fix unknown attribute disk storage_type provided by api library but not added back to resource

---

docs/resources/vm_qemu.md
proxmox/resource_vm_qemu.go

This might allow people to work around the issues in ticket #199 and also allow me to address the slow deployment issues that I've been having.
It's important to test this for a number of reasons:
- I did not add a unit test (I did look for clone_wait in there and was going to mimic that for additional_wait if it existed)
- I did not test this myself, as I'm not sure where I'd put the executable so it'd be available to a test VM, but not interfere with the rest of my VMs
- I didn't even compile it on account of not knowing how and not being able to find build instructions.  I tried `make` but it complained I didn't have go.  I installed golang-go and tried `make` again, but it complained about the nighmarish GOROOT and GOPATH environment variables that cause me problems with go 100% of …

Attempting to enable a workaround for #199

---

proxmox/resource_vm_qemu.go

Change the type of some parameter relative to diskt to INT since proxmox api expects 1|0 instead of True|False and casting the values into the provider seems a dirty hack
API Docs for reference:

change some QEMU resouce parameters from BOOL to INT

---

docs/resources/vm_qemu.md

This PR updates the QEMU resource documentation with data types, default values, and references to official Proxmox documentation where useful. This also organizes all the arguments and attributes into tables, rather than using bullet points, as (IMHO) it makes it easier to scroll through and view at-a-glance which options are available.
I have done my best to read through the code to determine how the arguments are processed by the provider, the proxmox-api-go lib, and the PVE API, so the descriptions can be as useful as possible. If I missed anything, or any of the descriptions are inaccurate, please feel free to suggest any all changes amendments you feel are necessary.

QEMU Resource Docs Update

---

README.md
docs/resources/lxc.md
docs/resources/vm_qemu.md

This pull request adds LXC resource documentation which currently does not exist. Links to official Proxmox documentation have been used where necessary, and additional LXC examples have been added too.
I have checked that everything will render correctly on [registry.terraform.io](https://registry.terraform.io) which can be verified [here](https://registry.terraform.io/tools/doc-preview) - just paste these changes into the text box at the top of the page.
Feedback appreciated as I plan on doing the same for the `proxmox_vm_qemu` resource at some point 🙂

Add LXC resource documentation

---

proxmox/resource_vm_qemu.go

Adds a configurable timeout when trying to get the VM IP from the guest agent. The initial implementation was ~60 seconds, which is too short if part of the cloud-init is to install qemu-guest-agent (and other things).
When finding VM's IP, use MAC address of net0. This prevents interfaces added to the VM later (like Docker) from being matched.

Make finding VM's IP more robust

---

proxmox/resource_vm_qemu.go

If you have a Proxmox QEMU template that supports cloud-init (perhaps you ran 'apt-get install cloud-init' during installation) then you need a "CloudInit Drive" attached to the VM to be able to pass the cloud-init parameters to the guest.  This adds a parameter 'cloudinit_cdrom_storage' that will configure a CloudInit Drive stored on the storage you specify. For example: cloudinit_cdrom_storage = "local-lvm".
Proxmox has an unfortunate "magic syntax" for these devices. Their documentation suggests that you do a 'config set' on a created template for something like 'local-lvm:cloudinit' to make it work.  Using a disk {} clause in the existing proxmox resource hierarchy doesn't work.

Allow specifying cloudinit_cdrom_storage to add a CloudInit Drive

---

docs/resources/vm_qemu.md
proxmox/resource_vm_qemu.go

The proxmox API supports tagging resources with a string of undefined format which is accessible via the configs endpoint.
I am adding this config field in the create, update, and read methods for qemu resources in an attempt to make PVE more usable with ansible dynamic inventory.
PVE will throw 400 errors if the supplied tag string contains unallowed characters which they do not list, but I have found to include ":", "|", "=", and "." precluding standard notation for key/value pairs. (PVE will accept a period if surrounded by alphanumerics)
Otherwise create, update, and delete function as expected and removing the tag field from an existing qemu resource will set the tag field back to null in PVE.
I attempted to update lxc in the same manner, but the PVE API itself throws 400 errors …

Adding support for tags with qemu resources

---

proxmox/resource_lxc.go

- Fix use `terraform import` command for import exist LXC has been crashed because cannot serialize `rootfs` config from API

Fix import exist LXC rootfs crash

---

docs/resources/vm_qemu.md

Previous instructions claim 0/1 to disable/enable, but from doing an import from an existing VM I discovered this field actually maps to the "minimum memory" field in the GUI - and I presume when it's not zero, enables the balloon device.

Update vm_qemu.md - corrected 'balloon' definition

---

proxmox/resource_lxc.go

When using this provider to create an lxc-container that contains one mountpoint, it fails with the following message:
```
Error: Proxmox Provider Error: proxmox API returned new parameter 'file' we cannot process
```
This is most likely caused due to the mountpoint endpoints return a `file` key, which the provider treats as unknown and aborts the entire apply. I could replicate this error in proxmox 6.2 & 6.3 using the following config:
```terraform
resource "proxmox_lxc" "container" {
target_node  = "pve"
ostemplate   = "local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz"
unprivileged = true
// Terraform will crash without rootfs defined
rootfs {
storage = "local-lvm"
size    = "2G"
}
mountpoint {
key     = "0"
slot    = 0
mp      = "/data/container"
storage = "local-lvm"
size    = …
```

Fix creating lxc with mountpoints

---

proxmox/resource_lxc.go

The only way to update the keys is to recreate the container entirely, as proxmox does not expose any API to do that. 
Fixes #207

Force lxc container recreate when ssh keys are updated

---

proxmox/resource_lxc.go

This PR makes it possible to set and retrieve tags on LXCs in the same way as for the QEMU instances. I have built the provider from this code and tested that it succesfully sets the tags and verified in the relevant config file in Proxmox that the tags are present. Doing a `terraform state show $resource` also shows the configured tags. 
This fixes compatibility with the Ansible dynamic inventory plugin for Proxmox, which supports tags for both LXCs and VMs:
https://github.com/ansible-collections/community.general/blob/48ef05def340588393075341c3b0b4e44f5fdab8/plugins/inventory/proxmox.py#L295

Add support for tagging LXCs

---

docs/guides/cloud_init.md
docs/resources/vm_qemu.md

This PR documents the `cloudinit_cdrom_storage` option which appears to be required when using `cicustom` to set the cloud-init drive content.
This will close #208

add cloudinit_cdrom_storage to options list

---

proxmox/resource_vm_qemu.go

When a VM is cloned as a linked clone, every time you ran terraform
apply, it would cause a force_new and destroy and readd the vm.
Since the API does not have a way to indicate if the device was a linked
clone or full clone, this was hardcoded.
Due to the way the `GetOk(key)` function works, this would always return
false, which would then cause the `full_clone` value to be reset back to
it's default, which is true.
Fixes by moving this to be a statically set value, since `full_clone` has
a default, which means it will always be set and we can force this in
the schema/state.
Also has a few linting, style changes from gofmt
Fixes #267

Fixes #265 - Fix full_clone = False reverts to true after first run

---

go.mod
proxmox/resource_vm_qemu.go

Hi all,
Would like to add the args parameter. This would enable passing arbitrary arguments to KVM.
For this to work I have already submitted the relevant code to "proxmox-api-go" last week.
My personal use case is enabling ignition for a flatcar linux template. An example value for the args parameter to enable ignition would be the following: "-fw_cfg name=opt/org.flatcar-linux/config,file=/var/lib/vz/snippets/flatcar.ign".
Theo

Added "args" parameter for passing arbitrary arguments to kvm. 

---

proxmox/resource_vm_qemu.go

This PR fixes #145 by waiting until the VM is stopped before deleting it.
I've tested the changes manually against our proxmox cluster (version 6.3).

Fix HA VM deletion

---

docs/resources/lxc.md
go.mod
go.sum
proxmox/resource_lxc.go

This change leverages the changes from https://github.com/Telmate/proxmox-api-go/pull/126 to allow setting the `hastate` parameter on LXC containers in addition to QEMU VMs.

Container HA support

---

go.mod
go.sum
proxmox/resource_vm_qemu.go

In case of multiple templates with same name, clone procedure chooses first template
returned by Proxmox. This commit forces it to choose template located on
target node if possible. It's helpful if templates use local storage and it's
impossible to clone templates between nodes, i.e. to avoid errors like:
"500 can't clone VM to node 'host2' (VM uses local storage)"
or
"500 storage 'xyz' is not available on node 'host1'"

clone: choose template located on target node if possible

---

go.mod
go.sum
proxmox/resource_lxc.go
proxmox/resource_vm_qemu.go

Currently, the endpoint /config does not give the pool, we have to obtain it manually. It may be interesting to refactor this to a single function.
I have also included the possibility of changing the pool of already created resources

Change pool management

---

proxmox/resource_vm_qemu.go

Fixes #409 but only the out of range panic.
If disks are removed from the plan Proxmox actually receives the correct configuration from Terraform but doesn't remove the unwanted/unlisted disks.
I couldn't find the corresponding api endpoint in the [Proxmox api viewer](https://pve.proxmox.com/pve-docs/api-viewer/index.html).
Anyway, I think this has to be first implemented into the api sdk.

Fix out of range panic

---

docs/resources/vm_qemu.md

Fixed the incorrect naming of the VGA memory variable.
Resolves Issue #417

fix naming of  memory item in the VGA block

---

proxmox/resource_vm_qemu.go

Template can contain block device. During cloning, plugin checks size and fails
if size is not same. In advance, it may be impossible to specify size correctly.
Let's consider "0" as unspecified size to skip check.

qemuvm: allow to unspecify size of cloned block device

---

Makefile

for better reproducible builds add trimpath, pull out sensitive user/system specific strings. github auto added end of file newline too. neither seems to cause issues with building or running provider
maintainer edits allowed

use trimpath for reproducibility

---

proxmox/resource_vm_qemu.go

I added the `aio` disk attribute, which was missing. And enforce the `scsihw` value. I'm not a go developer, so I took the `StringInSlice` method from this: https://github.com/hashicorp/terraform-provider-aws/issues/14601.

Add new `aio` disk attribute and endorce `scsihw` values

---

docs/index.md
examples/cloudinit_example.tf
examples/lxc_example.tf

If following the examples in the documentation for setting up the provider, users may not notice that the username changes from `terraform-prov` (e.g. [_here_](https://github.com/Telmate/terraform-provider-proxmox/blob/b2d39bbb0f6a7133fc922da31dd49792c94e85e9/docs/index.md?plain=1#L20)) to `terraform-user` (e.g. [_here_](https://github.com/Telmate/terraform-provider-proxmox/blob/b2d39bbb0f6a7133fc922da31dd49792c94e85e9/docs/index.md?plain=1#L43)), I don't know if either of these is preferred however I feel that they should be consistent.

Update example username in documentation to match username used earlier

---

proxmox/resource_vm_qemu.go

Hello, I use the provider, and on Hetzner we need set custom MTU on new VM interfaces when used VSWITCH.
I make changes in and wants to add the option. 
I checks locally and it works fine with proxmox 6x and 7.x

Allow set custom MTU.

---

proxmox/resource_lxc.go
proxmox/resource_vm_qemu.go

Currently mtu for LXC container is expected as string and there is no possibility to use this option.

Fix MTU type for LXC container

---

proxmox/validators.go

Hi !
According to the documentation and tests we must use the vmid 0 in order to have the vmid automaticaly defined to the next available ID. Example : 
```
resource "proxmox_vm_qemu" "vm" {
[...]
vmid = 0
[...]
}
```
But it's seems that in the new VMIDValidator() the value 0 is not accepted but only the value -1 or any value between 100 and 999999999. So the previous code wasn't valid.
This PR intend to fix this and allow the value 0 or any value between 100 and 999999999. This is tested on the version 2.9.6 and seems to be fully functional.
Feel free to edit or comment if I miss or forget something.
Kind Regards

Fix VMIDValidator for next available ID

---

proxmox/resource_lxc.go

Partially address #523.
Includes support for all boolean flags according to API.
Not sure what the best way to implement the mountoptions option is.

Support rootfs flags

---

proxmox/resource_lxc.go
proxmox/resource_pool.go
proxmox/resource_vm_qemu.go

Release 2.9.8 contain new version of proxmox-api. The previous version of
function GetPoolInfo returned as-is JSON payload, but new version trims
upper layer ("data"). It results into incorrect processing of pool data and
results into crash:
```
goroutine 11 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0x85011f900, {0xc0c640, 0x8502fc000})
/home/mizhka/repo/pgpro/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1503 +0x2fdf
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(...)
/home/mizhka/repo/pgpro/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1305
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0x85011f900, {0xc0c640, 0x8502fc000}) …
```

[fix-crash] Correct usage of changed proxmox-api (GetPoolInfo)

---

go.mod
go.sum

Related to #547 based on [2dc76fe536b0306ed18c6e887c3a9e3eebd45328](https://github.com/Telmate/proxmox-api-go/commit/2dc76fe536b0306ed18c6e887c3a9e3eebd45328) to print the exact error
Signed-off-by: Seena Fallah <seenafallah@gmail.com>

chore: bump proxmox-api-go dependency

---

proxmox/resource_vm_qemu.go

This can help to see the exact error when something like #547
Signed-off-by: Seena Fallah <seenafallah@gmail.com>

feat: add debug log on failed getting vm info

---

proxmox/resource_vm_qemu.go

In addition to setting throughput limits on disks in MB/s, it's also possible to set limits based on IOPS. This change adds the various IOPS related parameters to the disk configuration.

Add all IOPS related parameters from Proxmox API

---

proxmox/resource_vm_qemu.go

This PR ensure that backups is a int and not a bool. See
```
[ERROR] setting state: disk.1.backup: '' expected type 'int', got unconvertible type 'bool', value: 'true'
```
With this PR #284 should be fixed.

Backup should be a Int

---

Makefile

fix(build): Detect KERNEL on MacOS
- Detect MacOS kernel appropriately
- Lean on 'go tool dist env' to do more of the heavy lifting
On MacOS this behavior was exhibiting itself as KERNEL being a blank value.

fix(build): Detect KERNEL on MacOS

---

docs/index.md

`VM.Migrate` is required for vm migration, and changing `node`'s value of `proxmox_vm_qemu` resource triggers migration.
`Sys.Console` and `Sys.Audit` are required for modifying `hastate` and `hagroup` fields of a vm.

Update default role permissions

---

docs/index.md
proxmox/provider.go

`Sys.Modify` permission is required in order to modify the `startup` value of a VM. Since this provide purports to support modifying the `startup` field, add `Sys.Modify` to the list of minimum permissions. Also fix several inconsistencies in the docs around setting up the PVE role.
(3rd PR in a week "fixing" this. turns out permissions are hard, who knew?)

Add Missing Required Permission

---

proxmox/validators.go

Proxmox will generate a new MAC address when the provided value is empty and therefore MacAddressValidator function should not fail if the provided value is an empty string.

Do not return error if MAC address value is empty

---

docs/resources/lxc.md
proxmox/resource_lxc.go
proxmox/resource_lxc_disk.go

Hey guys! First of all, thanks for this great provider!
While using it, I noticed that the provider was not supporting sizes set in terabytes (ending in 'T') for LXC resources mountpoints and rootfs.
I don't know when the terabyte support was added to Proxmox, but I managed to build the provider locally and test it with success. I also found that the [pct CLI tool documentation](https://pve.proxmox.com/pve-docs/pct.1.html) details the valid sizes with the following regex ` \+?\d+(\.\d+)?[KMGT]? `.
Let me know if something needs to be fixed!

Support 'T' suffix for size attribute in LXC rootfs and mountpoints

---

proxmox/resource_vm_qemu.go

See the following correlated PR for an issue description and details:
https://github.com/Telmate/proxmox-api-go/pull/238
Currently, every `ipconfigX` config property is set to an empty string no matter what. This is due to the use of `.Get()`:
>Get returns the data for the given key, or nil if the key doesn't exist
in the schema.
>
>If the key does exist in the schema but doesn't exist in the configuration,
then the default value for that type will be returned. For strings, this is
"", for numbers it is 0, etc.
The problem is this will always return an empty string. That mixed with the `.(string)` cast makes for a bug.
The map value for each `ipconfig` entry should not be set unless it actually is set in the config. This PR uses `.GetOk()` instead, and only sets the map value when there …

Fix Ipconfigmap empty values

---

docs/resources/vm_qemu.md
examples/pxe_example.tf

Once the OS is installed, you have to boot on the disk.
With the opposite, it will always boot on the network
Cf: Issue [685](https://github.com/Telmate/terraform-provider-proxmox/issues/685)

change boot order in example

---

docs/guides/cloud_init.md

Updated cloud-init example guide - removed data block for template_file to use a more concise templatefile() function recommended by terraform

Updated cloud-init example guide

---

proxmox/provider.go

Using version v2.9.12 and configure provider using token method to communicate with PVE API, it complains
```
Error: cannot find provided user terraform-prov@pve!terraform-prov-token on proxmox
```
By checking the code, it seems that we should split user id from token_id string.

extract pm_user from pm_api_token_id when GetUserPermissions

---

docs/resources/vm_qemu.md

This PR removes the deprecated preprovision section from the `vm_qemu` resource documentation.
The section was strikethrough-ed but this does not show in the [Terraform Registry documentation page](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#preprovision), leading to some confusion.

docs: Remove deprecated preprovision section

---

proxmox/resource_vm_qemu.go

When you clone a template, ignore disk resize if media  is `cdrom`.

fix: Ignore disk resize if media is cdrom

---

docs/resources/vm_qemu.md
proxmox/resource_vm_qemu_test.go

Once the OS is installed, you have to boot on the disk.
With the opposite, it will always boot on the network
Cf: Issue https://github.com/Telmate/terraform-provider-proxmox/issues/685
> Changing some of the documentation is good.
> Out changing the documentation and the code is better
PS: I don't understand why the part between `<del>` and `</del>` is there. So I delete.

change PXE boot order and clean

---

proxmox/resource_lxc.go

Closes #753
Disclaimer: I did(/do) not know Go, so there probably is room for improvements. Please tell me how it can be improved  and I'll refactor.
First I tried matching simply based on name (e.g. `eth0`) however I've found this not to be desirable since names don't have to be unique and a simple rename would lead to recreation of a interface.
I then switched to using the Proxmox `id` since it does not have these flaws. I'm not 100% happy with the fact that I now need to drop the ids before applying the config. Suggestions for a better approach are welcome.
I've tested it quite a bit but certainly more testing would be good. I also don't know the impact on already existing states (since id is now added and was not there before).

lxc: implement deletion of network interfaces

---

proxmox/resource_vm_qemu.go

When specifying the volume of a disk, the file is empty. This breaks the check for cloud init where it is assumed the disk.file is a string.

fix crash when disk.file is nil

---

docs/resources/vm_qemu.md
examples/pxe_example.tf

Fixes #775.
- This creates bare minimum documentation for SMBIOS settings to the module documentation.
- This also fixes the backup example in the sample QEMU terraform file.

docs: add smbios to qemu docs + example

---

docs/resources/vm_qemu.md
proxmox/resource_vm_qemu.go

Fixes: #341 
The `size` parameter was ignored as it appears proxmox only supports two flash types--2m and 4m--and creates a 4M backing file regardless.
The `pre-enrolled-keys` flag was skipped due to the work needed to snake_case the key back/forth to meet terraform requirements. The default value (1) seems satisfactory for most scenarios. We can revisit if the need arises.
Changing `efidisk` properties will force a replacement in this initial implementation. 
While it's _technically possible_ to remove the efidisk and replace it, there appears to be some quirky proxmox behavior in this area. Specifically, proxmox will accept updates to the efidisk but drop those changes on the floor. Proxmox also exhibits strange behavior when removing an efidisk from a running hotplug-enabled machine. …

Add initial efidisk support

---

proxmox/data_ha_group.go
proxmox/provider.go
proxmox/resource_vm_qemu.go
proxmox/util.go

Imagine you have a cluster in which you migrate using High Availability Server. this is exactly the case I had. I have created a HA Group in Proxmox within which servers are automatically migrated in case of a failure or similar. 
With this code change it doesn't matter now. You can specify an array of possible nodes where the QEMU can be located. 
I also implemented my own change to your golang implementation (https://github.com/Telmate/proxmox-api-go/pull/262) to manage this with HA Groups.

Added multiple target nodes instead of a single node.

---

docs/index.md

I'm practicing Terraform in my home lab with Proxmox 8.0.3 and in the creation of my first instance LXC I came across the error that it was necessary the SND.use function for such a resource, so I took the opportunity to contribute in the doc.

Adding the role SND.use required for lxc in Proxmox 8.0.3

---

proxmox/resource_lxc.go

This PR essentially makes storage and size optional
I have tested this for my use cases and it seems to work well but I realize it's a bit naive. Where might I change docs or add a test? Size is required when storage is specified. Any advice on how might I inform the user of that misconfiguration?
⚠️ *The API PR must be merged before this one*
Issue: https://github.com/Telmate/terraform-provider-proxmox/issues/277
API PR: https://github.com/Telmate/proxmox-api-go/pull/271
Bind mount docs: https://pve.proxmox.com/pve-docs/pve-admin-guide.html#_bind_mount_points

Allow the creation of bind mounts for lxc containers

---

proxmox/resource_lxc.go

In Proxmox, if you provide no value to the "cores" option, the container will be allowed to use as many cores as it needs.
The current implementation of this provider defaults the cores to 1, and provides no way to override this to the "unlimited" mode. The default cores should be null to allow for unlimited, and provide the value for cores if you need to limit them

Make cores not default to 1 to allow for "unlimited" cores on containers

---

proxmox/resource_lxc.go

When I was reading the code for the code that handles the sizes of the lxc containers I found a small oversight. The comparison for the sizes letters checks for n instead of K.

Fix lxc container size: Accept K

---

proxmox/resource_vm_qemu.go

This PR alters `resourceVmQemuDelete` to attempt a graceful VM shutdown prior deletion (as opposed to the current method which performs a hard stop).  With the current behavior, DHCP reservations are left hanging until a timeout (which can take quite some time), leading to potentially lots of unavailable IP addresses.

Feat: Gracefully shutdown VM on deletion.

---

.gitignore
docs/resources/vm_qemu.md
proxmox/resource_vm_qemu.go

When trying to use this provider it is difficult to create a variable amount of static IP addresses which are unknown until install time. The quantity of network interfaces can be handled variably but the accompanying static IP addresses does not work to go along with that. 
I have modified this to allow dynamic IP addresses to be created while maintaining backwards compatibility for the current way of explicitly setting ipconfig0, ipconfig1, etc. 
To give an example of my desired usage:
variables.tf:
```
variable "networks" {
description = "defines NICs for the vm"
type = list(object({
model           = optional(string)
bridge          = optional(string)
vlan_tag        = optional(number)
gateway         = optional(string)
ip_address      = optional(string)
cidr_annotation = …
```

allow using dynamic list for ipconfig instead of hardcoding the index in the key

---

proxmox/resource_vm_qemu.go

resource_vm_qemu: allow . (dot) in name of virtual machine

---

docs/guides/developer.md
docs/guides/installation.md
go.yml

This adds a guide for new developers and corrects some commands which no longer work, filenames that changed and so on.
As an old developer who is new to this project, new to GoLang, and has never contributed to Terraform nor Proxmox, I found some things that were particularly troublesome in getting started.
1. The minimum version of GoLang required is newer than is shipped in any stable Debian release
2. There was a `go install` command in the documentation that didn't work (but apparently it's not needed if you check out the repo with `git`)
3. I copied the executable into the old place and it took me a while figure out why things weren't working as expected
4. I ran into the issue where you can't recompile and overwrite a provider's executable without modifying or deleting a lock file …

docs: New developer getting started guide

---

docs/guides/developer.md

Developers new to GoLang won't know how to have the compiler look at a local directory instead of getting dependencies from github. This documentation will be helpful when making changes that require changing proxmox-api-go in addition to the provider.
Thanks goes out to TheGameProfi for pointing this out. https://github.com/Telmate/terraform-provider-proxmox/issues/704#issuecomment-1873877454

docs: added instructions on how to use a local library

---

proxmox/resource_vm_qemu.go

The only required setting for adding the `cloud-init` disk will be `cloudinit_cdrom_storage`.
Closes #925

[3.0.1-rc1] Set `cloud-init` regardless of `cloud-init` settings

---

docs/resources/vm_qemu.md
proxmox/resource_vm_qemu.go

Noticed a lot of used are confused about the `CdRom` being added in slot `ide2`. Instead of configuring `iso` people can now configure any `CdRom`. The `iso` setting is removed without any backwards compatibility.
Booting from `CdRom` now is the default behavior when `pxe` is `false` and `clone` is empty.

[3.0.1-rc1] Remove `ISO` setting and unlock `ide2`

---

proxmox/resource_vm_qemu.go

Reverts Telmate/terraform-provider-proxmox#923
I've confirmed that removing this patch does not revert issue #702. In other words, you can deploy a VM with 2.9.11, switch your provider to version f9a1c063b978caa3a346d9278de146910758021b and do a `terraform apply` without having to manually change any tfstate files.

Revert "fix: enable new versions of providers to run on old tfstate files"

---

proxmox/resource_vm_qemu.go

resourceVmQemuCreate and resourceVmQemuUpdate can both return early due to errors. When this happens, we must ensure that we "unlock" the slot we have claimed for parallel execution. This is safe to do in a defer action because even if we manually "unlock" prior to the function return, the unlock action checks to ensure that the "lock" is held prior to attempting to return a slot to the pool.
Fixes #922

Fix parallel execution handling when returning early

---

examples/bug_reporting/README.md
examples/bug_reporting/issue.tf
examples/bug_reporting/provider.tf
examples/bug_reporting/vars.tf

Added terraform templates to guide people in creating tickets that make it easier for others to reproduce. If people use this, it will likely result in fewer issues because it will give people the tools to figure out how to resolve many of their own issues.
Related to #913

Add minimal example for reporting issues

---

docs/resources/lxc.md

Using commas forces "tags" update on every bump. One less surprise for new users.

DOC #951: mention correct delimiter, the one Proxmox uses internally

---

docs/resources/vm_qemu.md

The opening text is incorrect here, referencing scsi instead of virtio
The `disks.scsi` block is used to configure disks of type scsi.

Update to docs for Disks.Virtio Block

---

.github/workflows/manage_issues.yml

Changing the settings of stale-bot to never mark an pull requests and issue as stale that have someone assigned to it, or has one of the following labels: `bug` `community feedback` `documentation` `enhancement` `help need` `investigation` `question` `workflow`

Stale-bot exlusions

---

docs/resources/vm_qemu.md
go.mod
go.sum
proxmox/heper_qemu.go
proxmox/heper_qemu_test.go
proxmox/resource_vm_qemu.go
proxmox/util.go

supersedes #979
Reworks the control flow to make the code more testable.
Introduces the following variables:
- skip_ipv4
- skip_ipv6
- default_ipv6_address
If no `IP` can be found it now gives a `Warning` instead of an `Error` This fixes the problem the a `VM` can not be remove because in can't be read.
fixes #978
fixes #974

Rework: Agent get `IP`

---

docs/guides/cloud_init.md
docs/resources/vm_qemu.md
examples/cloudinit_example.tf
proxmox/resource_vm_qemu.go

- Make disk slot `ide3` usable.
- Remove `cloudinit_cdrom_storage` (unable to keep as deprecated due to complexity).
- Added `cloudinit` disk to the `disks` block.
- Minor code optimizations c585fa22a9ebb018c6e8705f2e7aeaa9498d6e8b 548c3ddc75cb471ec1a730a999e4aaa5ad20bb45.
closes #992
fixes #973

Move `cloudinit` disk to `disks` schema

---

docs/resources/vm_qemu.md
proxmox/heper_qemu.go
proxmox/heper_qemu_test.go
proxmox/resource_vm_qemu.go

fixes #1015
- Introduced `agent_timeout` to configure for how long we will try to get an IP address from the qemu guest agent before throwing a warning.
- Added test cases to `connectionInfo.hasRequiredIP()`.
- Improved explicitness of control flow.
Haven't tested yet.

Fix: v3.0.1-rc2: Stuck on still creating

---

.github/workflows/go.yml
.github/workflows/release.yml

goreleaser/goreleaser-action must use a version higher than 2

ci: bump workflow dependencies

---

docs/resources/cloud_init_disk.md

Fix cdrom part
- [`cd => cdrom`](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/resources/vm_qemu.md#disksxcdrom-block)
- extra variable `${local.iso_storage_pool}` fails and updates causes this issue:
`iso         = "cephfs:iso/tf-ci-***.iso" -> "cephfs:cephfs:iso/tf-ci-***.iso"`
```log
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "proxmox_vm_qemu" "cloud_vm_from_packer_template" {
id                     = "***/qemu/***"
name                   = "***"
tags                   = "***"
~ disks {
~ scsi {
~ scsi11 {
~ cdrom {
~ iso         = "cephfs:iso/tf-ci-***.iso" -> …
```

Doc fix: proxmox_cloud_init_disk

---

docs/resources/vm_qemu.md
go.mod
go.sum
proxmox/Internal/pxapi/dns/nameservers/nameservers.go
proxmox/Internal/pxapi/guest/sshkeys/sshkeys.go
proxmox/heper_qemu.go
proxmox/heper_qemu_test.go
proxmox/resource_vm_qemu.go
proxmox/util.go
proxmox/util_test.go

Makes terraform compatible with https://github.com/Telmate/proxmox-api-go/pull/339.
Add `ciupgrade` property.  (required work upstream)
fixes #997 (Tested)
When `network` is set in `cicustom` we continue with trying to get the ip.  (required work upstream)
fixes #1011
`searchdomain`, `nameserver`, `ipconfig0-15` can now be removed. (required work upstream)
fixes #1042 (Tested)

Update `cloud-init` for proxmox-api-go #339

---

proxmox/resource_vm_qemu.go

I've fixed small typo, now value mbps_wr_concurrent should be retrieved correctly.
Fixes #1054

Fix retrieving mbps_wr_concurrent value

---

docs/index.md

In order to use proxmox_cloud_init_disk the TerraformProv role needs Datastore.AllocateTemplate privilege. It is described in proxmox api docs https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/upload.

Added Datastore.AllocateTemplate priv to use proxmox_cloud_init_disk.

---

go.mod
go.sum
proxmox/resource_vm_qemu.go

Allows for clearing the description.
Fixes #771

fix: can't clear description

---

proxmox/provider.go
proxmox/resource_vm_qemu.go

Fix: force an API call to retrieve the next VM id from Proxmox API rather than relying on local state.
We've found in our day to day operations that an **existing** VM was being overwritten. This patch should fix it.

Patch for VM ID where a VM might be overwritten

---

proxmox/resource_vm_qemu.go

The pci's `id` is currently not being handled in code and it causes for the terraform/tofu/terragrunt run to fail with:
```
Error: Invalid address to set: []string{"hostpci", "0", "id"}
```
Reported in 
* https://github.com/Telmate/terraform-provider-proxmox/issues/1029 
This patch fixes this scenario. Tested with Proxmox 8.2+

Fix `Invalid address to set` for hostpci configuration

---

.github/workflows/go.yml

All CI task now run in parallel and aren't blocked by one another.
Removed golint as it's deprecated.

CI parallel

---

docs/resources/vm_qemu.md
go.mod
go.sum
proxmox/resource_vm_qemu.go

Fixes #1034
Terraform half of https://github.com/Telmate/proxmox-api-go/pull/359

Reimplement Serials

---

proxmox/resource_vm_qemu.go

Configuring usb devices currenlty does not work and leads to an error #1032.
` Error: Invalid address to set: []string{"usb", "0", "id"} `
@lucian-tx fixed a similar issue for the hostpci config (#1029), which also works for the usb config.

Fix invalid address to set for usb config

---

docs/resources/vm_qemu.md
proxmox/resource_vm_qemu.go

Fix: `disk` block diff

---

docs/resources/vm_qemu.md

Configuring the MTU for a qemu vm is already implemented, but is it not currently documented.
added in #498 
https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L364

add MTU documentation for qemu vm

---

go.mod
go.sum

Issue described in #1133 has been fixed upstream.
Resolves #1133

chore: bump proxmox-api-go version

---

docs/index.md
proxmox/provider.go

Converted the stings to constants, to make it easier to see where things are referenced.
Converted the documented setting to a table to be in style with the rest of the documentation.
Adding a warning to keep `pm_parallel` set to `1` #1136

Add waring for `pm_parallel`

---

proxmox/resource_vm_qemu.go

Special thanks to @TomyLobo for noticing this regression in https://github.com/Telmate/terraform-provider-proxmox/commit/641d0963dd6ae37409206139184c310d655ce058#diff-104365919f693375882979581d9f36f5266991eef361948e56c220931fe886ddL1615
Originally fixed in #1039
Related to #1023
Closes #1154

fix: regression #1154

---

proxmox/resource_storage_iso.go

This PR fixes the ``proxmox_storage_iso`` resource by replacing the hardcoded ``/tmp`` path with a cross-platform temporary dir using ``os.TempDir()``.
``proxmox_storage_iso`` was broken on windows machines.

fix: fixes proxmox_storage_iso temp dir path

---

proxmox/resource_lxc.go

Setting the boolean value would have no effect when creating the lxc.
This is because the check to start it was in an if block, which was executed only if the container was updated, not created.
Move the start of the container out of the if block, so it is checked everytime.

Enable starting an lxc container which was just created

---

docs/resources/vm_qemu.md
go.mod
go.sum
proxmox/Internal/resource/guest/qemu/pci/schema.go
proxmox/Internal/resource/guest/qemu/pci/sdk.go
proxmox/Internal/resource/guest/qemu/pci/terraform.go
proxmox/resource_vm_qemu.go

Full Qemu PCI support.
- Adds `pci` setting for use in modules.
- Adds `pcis` setting.
- Deprecates `hostpci`.
Closes #1157 as it supersedes it.
Resolves #1029
Resolves #1107

Feat: Full Qemu PCI support

---

docs/guides/cloud_init.md
docs/resources/vm_qemu.md
examples/cloudinit_example.tf
examples/pxe_example.tf
proxmox/Internal/resource/guest/qemu/cpu/schema.go
proxmox/Internal/resource/guest/qemu/cpu/sdk.go
proxmox/Internal/resource/guest/qemu/cpu/terraform.go
proxmox/resource_vm_qemu.go

Moved all CPU related code to it's own package.
The `cpu` key has been deprecated in favor of `cpu_type` to allow for the continuation of #1149.

refactor: move cpu code to package & deprecate `cpu`

---

docs/index.md
proxmox/provider.go

fix: provider insecure by default

---

go.mod
go.sum
proxmox/data_ha_group.go
proxmox/provider.go
proxmox/resource_cloud_init_disk.go
proxmox/resource_lxc.go
proxmox/resource_lxc_disk.go
proxmox/resource_pool.go
proxmox/resource_storage_iso.go
proxmox/resource_vm_qemu.go

Other half of https://github.com/Telmate/proxmox-api-go/pull/387
The provider can now be canceled with `^c` instead of having to forcefully kill it.

feat: add `context`

---

docs/guides/cloud-init getting started.md

"id" is now required in network block:
$ tofu plan
│ Error: Missing required argument
│ 
│   on main.tf line 51, in resource "proxmox_vm_qemu" "cloudinit-example":
│   51:   network {
│ 
│ The argument "id" is required, but no definition was found.

Update cloud-init getting started.md

---

proxmox/Internal/resource/guest/pool/schema.go
proxmox/resource_lxc.go
proxmox/resource_vm_qemu.go

Use config for pool instead of vmref.
Move pool of guests to seperate package
Related to #1117

Move guest `pool` to package

---

proxmox/Internal/resource/guest/qemu/network/schema.go
proxmox/Internal/resource/guest/qemu/network/terraform.go

Ensures that the return value for MAC is in the same case as the input in the .tf file, regardless of it's case in PVE.
Removes the diffsuppression for MAC.
resolves #1182

feat: return same case for MAC

---

proxmox/resource_vm_qemu.go

Issue caused by #1243
@maksimsamt found the issue you ran into during the testing of #1182, turns out it cloned into the global scope instead of the scope of the pool.

fix: VM not cloned into pool

---

proxmox/Internal/resource/guest/qemu/tpm/schema.go
proxmox/Internal/resource/guest/qemu/tpm/sdk.go
proxmox/Internal/resource/guest/qemu/tpm/terraform.go
proxmox/resource_vm_qemu.go

This MR adds features in two commits.
1. pre_enrolled_keys to the efidisk stanza.  This gets translated to the pre-enrolled-keys flag to turn on secure boot.
2. Add tpmstate stanza to configure the tpm in the VM.  This takes a storage location and a version.
These were tested against v3.0.1-rc6.  The master tree has additional issues.
The code difference between the two points on the tree is the pxapi rename to pveSDK.

Feat tpmstate efi secureboot

---

docs/resources/lxc.md
docs/resources/vm_qemu.md
go.mod
go.sum
proxmox/Internal/resource/guest/node/schema.go
proxmox/Internal/resource/guest/node/sdk.go
proxmox/Internal/resource/guest/node/terraform.go
proxmox/resource_lxc.go
proxmox/resource_vm_qemu.go
proxmox/util.go

When using `target_nodes` the guest will be move to one of the guests at random, and it will stay there until the node is not in the list specified by `target_nodes`.
Adds `current_node` which will display the name of the node the guest is currently on.
`target_node` and `target_nodes` have been made mutually exclusive.
Solves the issues of the following tickets.
closes #1031
closes #1081
Solved due to dependency version update. 
closes #1259

Fix: multiple target nodes

---

docs/index.md

Hello,
It just fixes a typo in the env var, found on the Terraform documentation page.
Thanks for your work!

docs: fix bad env var name for secret

---

docs/resources/vm_qemu.md
go.mod
go.sum
proxmox/resource_vm_qemu.go

Fixed and issue where `agent_timeout` would never be set.
Increased the default `agent_timeout` from 60 to 90 seconds.
Refactored the `getPrimaryIP()` func to reduce nesting and complexity.
Updated proxmox-api-go
Closes #1106

fix: agent_timeout never set

---

proxmox/Internal/resource/guest/sshkeys/schema.go

The `EOF` syntax adds extra `\n` characters which will result in empty items or items with whitespace, which would be detected as invalid ssh-keys.
Resolves #1280

fix: 3.0.1-rc7 unable to set sshkeys with EOF

---

proxmox/resource_lxc.go

Logic for using a dynamic id was inverted.
When the id would be dynamic it would also have been `0`.
Resolves #1279

fix: 3.0.1-rc7 doesnt create the vmid specified on tf

---

proxmox/Internal/resource/guest/node/schema.go
proxmox/Internal/resource/guest/node/sdk.go
proxmox/resource_lxc.go
proxmox/resource_vm_qemu.go

Sets a minimum of `1` node when `target_nodes` is specified.
Return en error when `target_node` and `target_nodes` aren't specified.
Resolves #1297

Fix panic when no target nodes specified

---

go.mod
go.sum
proxmox/Internal/resource/guest/qemu/disk/schema.go
proxmox/Internal/resource/guest/qemu/disk/sdk.go
proxmox/Internal/resource/guest/qemu/disk/sdk_disk.go
proxmox/Internal/resource/guest/qemu/disk/sdk_disks.go
proxmox/Internal/resource/guest/qemu/disk/terraform.go
proxmox/Internal/resource/guest/qemu/disk/terraform_disk.go
proxmox/Internal/resource/guest/qemu/disk/terraform_disks.go
proxmox/Internal/resource/guest/qemu/disk/warning.go

Adds the `ignore` option to `disk` and `disks`.
With this setting Terraform will ignore the state of the disk, and **NOT** modify or remove it.
Closes #1206

feat: add `ignore` option to `disk` & `disks`

---

proxmox/Internal/resource/guest/qemu/cloudinit/helper.go
proxmox/Internal/resource/guest/qemu/cloudinit/schema.go
proxmox/resource_vm_qemu.go

Resolves #1311
Moved part of the cloud-init code to a separate package as we don't make additions of this kind in [proxmox/resource_vm_qemu.go](https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go) anymore.

fix: `nameserver` reports diff when delimiter changes

---

proxmox/Internal/resource/guest/qemu/disk/schema.go
proxmox/Internal/resource/guest/qemu/disk/terraform_disk.go
proxmox/Internal/resource/guest/qemu/disk/terraform_disks.go

Slot 4 is missing from `disk`
Removed a redundant call to parse the `cdrom`.
Closes #1124
Except for the disk size, #1124 this has been resolved by #1306

Fix missing `IDE` slot

---

docs/index.md

Ran into some problems with the docs because of the exclamation mark in bash. 
Works for me when using single quotes. So I thought I'll send a quick patch.

fix(doc): use single quotes for PM_API_TOKEN_ID env var

---

proxmox/Internal/resource/guest/qemu/cpu/schema_legacy.go

Change deprecation message from `use cpu.cores instead` to `use 'cpu { cores = }' instead` to improve clarity.
Closes #1344

refactor: deprecation message

---

proxmox/resource_vm_qemu.go

Removes hard coded reboot, in favor of letting the SDK handle it.
Resolves: #1345

fix: unneeded hardcoded reboot

---

go.mod
go.sum
proxmox/Internal/resource/guest/node/sdk.go
proxmox/helper_guest.go
proxmox/helper_guest_test.go
proxmox/resource_cloud_init_disk.go
proxmox/resource_lxc.go
proxmox/resource_lxc_disk.go
proxmox/resource_pool.go
proxmox/resource_storage_iso.go
proxmox/resource_vm_qemu.go

Fixes the issue where the desired node isn't honored.
- Split-up the code to make it testable.
- Updated dependencies.
- Includes upstream changes.
Related to #1375

Fix: Clone uses wrong node when identical templates exist on multiple Proxmox nodes

---

docs/guides/cloud-init getting started.md

This change fixes a bug in the Terraform code snippet. Terraform follows semver rules and its version constraints only allows pre-release versions with `=` operator.
ref: https://developer.hashicorp.com/terraform/language/expressions/version-constraints#specify-a-pre-release-version

Update cloud-init getting started docs

---

docs/index.md

Hi, 
Privilege `VM.Monitor` has been drop in proxmox 9. According to https://github.com/Telmate/terraform-provider-proxmox/pull/1382 here is just a fix for Documentation. 
see https://pve.proxmox.com/wiki/Roadmap#:~:text=Drop%20the-,VM.Monitor,-privilege%20and%20instead%20require%20the

Update Proxmox 9 privileges in documentation

---

go.mod
go.sum
proxmox/helper_guest.go

Fixes #1394 by deleting the HaResource before the guest is deleted.

Fix: Terraform destroy fails if VM is in HA.
