- docs/terraforminit.md
Just a quick document to help people setup the provider if terraform doesn't find it.
> Documents for copying the provider so it works

- proxmox/resource_vm_qemu.go
> Show message when neither clone nor iso is set

- proxmox/resource_vm_qemu.go
Closes #37 
Requires https://github.com/Telmate/proxmox-api-go/pull/19
> Fix VM name changing

- .travis.yml
I believe this is enough to simply see what builds and does not build.
You will need to set up an account at travis: https://travis-ci.com/ and set up this repository to build.
> Basic travis pipeline

- examples/cloudinit_example.tf
- proxmox/resource_vm_qemu.go
Added an examples directory with a example file for the terraform script. This is following a common practice for other modules and might be handy for one or an other.
> Add examples

- proxmox/resource_vm_qemu.go
> Add missing agent on update

- Makefile
- README.md
I actually had to do i propose in the README update to actually be able to build.
So this might possibly interest you.
Cheers,
> README: Update Makefile/readme to ease local build

- README.md
- proxmox/resource_vm_qemu.go
This feature allows you to create a serial interface to activate xterm.js in Proxmox
> Add support for serial devices

- proxmox/provider.go
@V-Paranoiaque can you check this version out?
> support PM_OTP_PROMPT for ondemand interactive OTP

- README.md
- examples/cloudinit_example.tf
- proxmox/resource_vm_qemu.go
Hello
It's now possible to:
- Change the type of CPU
- Set CPU flags
- Enable Numa
- Enable the hotplug feature for network,disk,cpu,memory and usb
> Add CPU customization features and hotplug

- proxmox/resource_vm_qemu.go
With the parameters ``full_clone`` we can choose to make a full or linked clone. 
This PR need the [PR 52](https://github.com/Telmate/proxmox-api-go/pull/52) on promox-api-go to work. 
I test this PR on Promox 6.
> Add choice between full or partial clone

- README.md
- go.mod
- go.sum
- proxmox/resource_vm_qemu.go
Manage the HA for a VM, PR also done in the API repo
> New feature, HA management

- .gitignore
- .travis.yml
- Makefile
- cmd/terraform-provider-proxmox/.gitignore
- cmd/terraform-provisioner-proxmox/.gitignore
Hey,
I updated the Makefile to get all benefits from go modules. Also I imroved the caching go modules in travis-ci.
ping @ggongaware 
Signed-off-by: solidnerd <niclas@mietz.io>
> Improve Makefile for go modules and travis

- go.mod
- go.sum
- proxmox/resource_vm_qemu.go
This PR add the feature to be able to migrate vm to another node.
> Node migration

- README.md
- proxmox/resource_vm_qemu.go
Please see [this](https://github.com/Telmate/terraform-provider-proxmox/issues/140) for a discussion around this feature.
> Cloud init custom config file

- proxmox/resource_vm_qemu.go
Hi, 
For the idempotence as mentioned in the issues #88 & #112.
> Rollback to computed mac address

- proxmox/resource_vm_qemu.go
This patch allows to have a config like this:
```
resource "proxmox_vm_qemu" "cloudinit-vm" {
name = "test.xyz.com"
clone = "t-centos-7.7"
agent = 1
os_type = "cloud-init"
ipconfig0 = "ip=dhcp"
...
connection {                  
user = "packer"                           
password = var.ssh_password
// self.ssh_host will automatically be set to the dhcp address
host = self.ssh_host
}                                       
provisioner "remote-exec" {
inline = [  
// here you will see the actual ip address        
"/sbin/ip a"  
]      
}
```
The code was partly copied from https://github.com/hashicorp/packer/blob/master/builder/proxmox/builder.go where dhcp+qemu-guest-agent are the only way to connect to the vm.
> get ip address of resource_vm_qemu if cloud-init uses dhcp

- docs/resource_vm_qemu.md
- proxmox/resource_vm_qemu.go
Completes the feature `vmid` that has been added to LXC.
> add vmid to vm qemu resource

- docs/resource_vm_qemu.md
- examples/cloudinit_example.tf
- proxmox/resource_vm_qemu.go
This PR adds Discard option for disks and includes changes form PR #146  + docs
> Added SSD emulation and Discard options. Updated docs and examples

- proxmox/resource_vm_qemu.go
Added SSD emulation configuration option
> Added SSD emulation configuration option

- go.mod
- go.sum
- proxmox/resource_vm_qemu.go
> Add kvm flag and default it to true.

- docs/provider.md
- go.mod
- go.sum
- proxmox/provider.go
- proxmox/provisioner.go
Making working with https://github.com/Telmate/proxmox-api-go/pull/86
Resolve #202
> support timeout in provider options

- proxmox/resource_vm_qemu.go
Add step reboot VM when success update resource state.
> :hammer: Add reboot to step to apply PVE change

- .goreleaser.yml
Add goreleaser config for the build which are required by Terraform Registry for publishing custom providers.
Check out:
- https://registry.terraform.io/providers/ondrejsika/proxmox/latest
- https://github.com/Telmate/terraform-provider-proxmox/issues/218#issuecomment-696013579
Let me know if you want to help with publishing process.
> Add goreleaser.yml (for Terraform Registry builds)

- docs/installation.md
Updated installation.md doc to reflect TF v0.13 filesystem layout.
> update for TF 0.13

- proxmox/resource_vm_qemu.go
This is an improvement for my older pull request #169. The current code waits until the qemu-guest-agent becomes alive and presents the interfaces with their ip addresses (from dhcp) running on the qemu vm. In a loop checks for loopback addresses, which it skips. In the end the first non-loopback address is passed to terraform. This works as long as you stay with ipv4.
In the last time i frequently ran into problems, where terraform was showing something like "fe80" or an empty string as target address. This was caused by a vm which has ipv6 enabled, so that something like fe80::a6f5:7385:cf7d:3f61 showed up, which, after splitting address:port, became fe80. The empty string probably came from a scenario, where the qemu agent was running, but dhcp had not aquired an adddress yet.
So the …
> if resource_vm_qemu with cloud-init uses dhcp, then wait for a global unicast ipv4 address

- proxmox/resource_vm_qemu.go
Proxmox won't supply values for terraform-provider only keys on import, thus they should be set to default values when not explicitly defined in resource configuration.
Network tag will also be set to null in tfstate on import when not set in Proxmox, though terraform-provider-proxmox expects it to be `-1` when not used, which leads to resource being recreated (which is not what we want).
> populating undefined keys when importing

- docs/guides/cloud_init.md
Documentation about Cloud-Init so nobody ever has the same experience I had in https://github.com/Telmate/terraform-provider-proxmox/issues/272
> Improved Cloud-Init documentation

- docs/guides/cloud_init.md
Fixed a broken link. :facepalm:
> fixed typo

- proxmox/resource_vm_qemu.go
Currently, when you are using cloud-init and do not specify the `ipconfig0` parameter, the provider crashes because it expects either `ip=dhcp` or an IP address. The empty string gets treated as an IP address and this will lead to a panic in the provider and a crash in terraform.
I modified the code to simply check if the `ipconfig0` parameter is set at all.
_The relevant part in crash.log:_
```
[...]
panic: runtime error: index out of range [1] with length 0
goroutine 65 [running]:
.../Telmate/terraform-provider-proxmox/proxmox.initConnInfo(0xc0004aa980, 0xc00048a550, 0xc000312780, 0xc0004853a0, 0xc0004854a0, 0xc000485330, 0x0, 0x0)
.../Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1498 +0x12da
[...]
```
> Fix crash when using cloud-init without ipconfig0 set

- docs/resources/vm_qemu.md
Change some parameters according to PR #287  (and a small fix on discard)
> change resource parameter types

- proxmox/resource_vm_qemu.go
- proxmox/resource_vm_qemu_test.go
Currrently any changes made to vm_qemu resources triggers a stop&start task for the VM.
This is not always necessary, for example you can rename a VM while it's running.
My changes: I introduced a new variable in the schema called `reboot_required`. Whenever a "critical" configration parameter changes, this variable will be set to `true`. The end of the resource update will power cycle the VM only if this variable is set to `true`.
Regarding shutdown: currently, it stops the VM instead of a graceful shutdown. This always works, but definitelly not safe in production environment. So I rewritten that part to try a graceful shutdown first, and if that fails it will try to stop the VM forcefully.
This should fix issue #256 as well.
> Reboot only when necessary + better shutdown logic

- README.md
- docs/guides/installation.md
-Update README
-Add `export GO111MODULE=on` to resolve plugin installation as described [here](https://github.com/Telmate/terraform-provider-proxmox/issues/290)
> Fix provider installallation

- proxmox/resource_vm_qemu.go
In this PR I added a new var for the provisioners `default_ipv4_address`. Named it after the vsphere provider var.
I don't know if the change makes sense in this way. The whole part to determine the ipv4 address within the cloud init part where moved out of this condition to set the var in general. As far as I can tell, it shouldn't make a difference but I can't say it for sure.
I tested it in my setup without `ssh_forward_ip` defined and cloud init configured.
> Add default_ipv4_address var for provisioners

- go.mod
More detail issue at 
https://github.com/Telmate/proxmox-api-go/issues/111
> Update proxmox-api-go to fix issue parse IPv6

- docs/resources/lxc.md
- go.mod
- go.sum
- proxmox/resource_lxc.go
> Implement lxc clone feature with docs

- docs/resources/vm_qemu.md
- go.mod
- go.sum
- proxmox/resource_vm_qemu.go
Hi,
This P.R brings newly added USB devices support of proxmox-api (https://github.com/Telmate/proxmox-api-go/pull/155).
> feat(qemu): add usb devices support

- proxmox/resource_lxc.go
Experimental feature added with Proxmox 7.
> lxc mknod feature flag support

- proxmox/resource_lxc.go
> Release lock before attempting to read

- proxmox/resource_lxc.go
> Start parameter was not taken into account when clone of LXC was done

- docs/resources/vm_qemu.md
I was looking for import capabilities and found it in the source code, but did not find any documentation. I tested it, and the import function works, so I wrote some like documenting it.
Other providers place a paragraph about importing at this location as well.
> Added Import documentation

- docs/resources/vm_qemu.md
- proxmox/resource_vm_qemu.go
I implemented support for the interfaces 6-15 as mentioned in #555 . (`ipconfig6` to `ipconfig15`)
> Support for network interfaces 6-15

- go.mod
- go.sum
- proxmox/resource_vm_qemu.go
https://github.com/Telmate/proxmox-api-go/pull/216 changed the types of the cloud-init config.
- Update github.com/Telmate/proxmox-api-go to latest version.
- Changed how the cloud-init properties are mapped.
> Fix: type conflict for cloud-init.

- proxmox/provider.go
This is the Terraform half of https://github.com/Telmate/proxmox-api-go/pull/228
#653 fixes type issues I came across while working on this.
> Refactor: proxmox-api-go [user config]

- proxmox/resource_vm_qemu.go
As I mentioned in #710, this options change do not require vm recreation.
> Remove ForceNew from ip option

- proxmox/resource_lxc.go
- proxmox/resource_vm_qemu.go
fix smbios
fix oncreate vs vm_state race condition
make some changes to be more coherent with hashicorp sdk
> various stability & performance fixes

- docs/resources/vm_qemu.md
- proxmox/resource_vm_qemu.go
Hello,
This small patch to make possible set disk `serial` or `wwn` param.
Thank you.
> Add disk parameters serial and wwn

- proxmox/resource_vm_qemu.go
> don't reboot on update if automatic_reboot is disabled

- docs/index.md
Appearantly proxmox8 requires the SDN.Use permission as well
> added proxmox8 specific permission

- proxmox/provider.go
- proxmox/resource_storage_iso.go
Was trying to automate my setup and found this missing.
It add the ISO storage resource which accepts iso url and pushes it through the proxmox api
> Add ISO Storage resource

- README.md
- proxmox/resource_vm_qemu.go
I'm very new to proxmox in general. Currently getting my first installation going on some servers as we speak. But as I was reading through the documentation, I saw this bullet point and figured it was worth pulling some low hanging fruit. Please let me know if I've overlooked some requirements or documentation or something obvious to you all, and I'll get it fixed.
> add validation to vm_qemu name field

- proxmox/resource_vm_qemu.go
> fix: `machine` diff to `null`

- proxmox/resource_vm_qemu.go
> fix `qemu_os` diff to `null`

- proxmox/resource_vm_qemu.go
> Remove redundant warning

- proxmox/resource_vm_qemu.go
> feat: stop VM when deleting

- go.mod
- go.sum
- proxmox/resource_vm_qemu.go
Terraform half of: https://github.com/Telmate/proxmox-api-go/pull/349
Fixes #1045
> refactor: use new memory implementation

- go.mod
- go.sum
- proxmox/resource_vm_qemu.go
- proxmox/util.go
Terraform half of https://github.com/Telmate/proxmox-api-go/pull/354
> CPU update

- proxmox/resource_vm_qemu.go
Previously assumed `net0` would exist now loops over `net0` till `net16` until it finds one. When no network adapter is found we skip getting the IP.
fixes #1074
> Fixes: panic `net0` does not exist

- docs/resources/vm_qemu.md
- proxmox/errors.go
- proxmox/resource_vm_qemu.go
Implementation of the new `disk` schema.
Closes #986
> feat `disk` schema

- docs/guides/cloud-init getting started.md
Closes #1105 
Closes #1104
Closes #959
> docs: Cloud-Init getting started guide

- docs/resources/vm_qemu.md
- examples/cloudinit_example.tf
- examples/pxe_example.tf
- go.mod
- go.sum
- proxmox/Internal/resource/guest/qemu/network/schema.go
- proxmox/Internal/resource/guest/qemu/network/sdk.go
- proxmox/Internal/resource/guest/qemu/network/terraform.go
- proxmox/Internal/util/util.go
- proxmox/heper_qemu_test.go
- proxmox/resource_lxc.go
- proxmox/resource_pool.go
- proxmox/resource_vm_qemu.go
- proxmox/util.go
Re-implement the qemu network interfaces.
Add required `id` property.
closes #1000
closes #1027
> Reimplement qemu network interfaces

- docs/resources/vm_qemu.md
- go.mod
- go.sum
- proxmox/Internal/resource/guest/qemu/usb/schema.go
- proxmox/Internal/resource/guest/qemu/usb/sdk.go
- proxmox/Internal/resource/guest/qemu/usb/terraform.go
- proxmox/Internal/validator/validator.go
- proxmox/resource_vm_qemu.go
Rework the QemuUSB settings to be less error prone.
closes  #1032
> Rework QemuUSB

- proxmox/Internal/resource/guest/qemu/network/schema.go
- proxmox/Internal/resource/guest/qemu/network/sdk.go
- proxmox/Internal/resource/guest/qemu/network/terraform.go
- proxmox/Internal/resource/guest/qemu/usb/schema.go
- proxmox/Internal/resource/guest/qemu/usb/sdk.go
- proxmox/Internal/resource/guest/qemu/usb/terraform.go
- proxmox/resource_vm_qemu.go
Fixed an issue where we were accessing an array item outside of the range.
Minor performance improvements.
> Fix: array out of bounds

- proxmox/Internal/resource/guest/qemu/pci/sdk.go
- proxmox/Internal/resource/guest/qemu/usb/sdk.go
USB & PCI devices not removed when blocks are unset.
> fix: devices not removed

- docs/resources/vm_qemu.md
- proxmox/Internal/resource/guest/qemu/network/sdk.go
> hotfix: vlan not set

- docs/index.md
- Added specific command to create an API token for the Proxmox provider
> docs: update API key support information in index.md

- proxmox/Internal/resource/guest/qemu/disk/terraform_disks.go
> fix: refrenced wrong disk type

- go.mod
- go.sum
- proxmox/Internal/resource/guest/node/schema.go
- proxmox/provider.go
- proxmox/resource_lxc.go
- proxmox/resource_vm_qemu.go
Adds validation of node name.
Closes #1208
> feat: validate node name

- proxmox/Internal/resource/guest/vmid/schema.go
- proxmox/Internal/resource/guest/vmid/terraform.go
- proxmox/resource_lxc.go
- proxmox/resource_vm_qemu.go
- proxmox/validators.go
> Fixes: vmid output is null

- go.mod
- go.sum
- proxmox/Internal/resource/guest/qemu/disk/terraform.go
- proxmox/Internal/resource/guest/vmid/schema.go
- proxmox/Internal/resource/guest/vmid/terraform.go
- proxmox/provider.go
- proxmox/resource_lxc.go
- proxmox/resource_vm_qemu.go
Terraform half of https://github.com/Telmate/proxmox-api-go/pull/399
> Refactor: use type `GuestID`

- docs/resources/vm_qemu.md
- proxmox/Internal/resource/guest/qemu/pci/schema.go
- proxmox/Internal/resource/guest/qemu/pci/sdk.go
- proxmox/Internal/resource/guest/qemu/pci/terraform.go
Add `mdev` property to `pci` and `pcis`.
Closes #1258
> feat: add PCI `mdev` property

- proxmox/Internal/resource/guest/qemu/network/sdk.go
> fix: MTU = 1 not working

- docs/resources/vm_qemu.md
forgot to add documentation for the new feature in #1306
> docs: `ignore` setting of `disk` & `disks`

- proxmox/Internal/resource/guest/qemu/disk/schema.go
- proxmox/Internal/resource/guest/qemu/disk/terraform_disks.go
Fixes a panic when reading disks into Terraform.
resolves #1315
> fix: qemu `disks` panic

- docs/guides/developer.md
- docs/guides/installation.md
Fix broken link and properly format markdown.
Resolves #1287
> Fix broken link and fromat markdown

- proxmox/Internal/resource/guest/qemu/disk/terraform_disk.go
Fixes nil pointer exception.
Resolves #1354
> Fix: Qemu nil pointer exception

- proxmox/Internal/resource/guest/node/schema.go
- proxmox/Internal/resource/guest/node/sdk.go
- proxmox/Internal/resource/guest/node/terraform.go
Fix the nil pointer exception when importing LXC guests.
Resolves #1338
> Fix: LXC import panic

- go.mod
- go.sum
> chore: bump proxmox-api-go

- go.mod
- go.sum
- proxmox/Internal/resource/guest/lxc/_sub/acl/schema.go
- proxmox/Internal/resource/guest/lxc/_sub/acl/sdk.go
- proxmox/Internal/resource/guest/lxc/_sub/acl/terraform.go
- proxmox/Internal/resource/guest/lxc/mounts/schema.go
- proxmox/Internal/resource/guest/lxc/mounts/schema_mount.go
- proxmox/Internal/resource/guest/lxc/mounts/schema_mounts.go
- proxmox/Internal/resource/guest/lxc/mounts/sdk.go
- proxmox/Internal/resource/guest/lxc/mounts/sdk_mount.go
- proxmox/Internal/resource/guest/lxc/mounts/sdk_mounts.go
- proxmox/Internal/resource/guest/lxc/mounts/terraform.go
- proxmox/Internal/resource/guest/lxc/mounts/terraform_mount.go
- proxmox/Internal/resource/guest/lxc/mounts/terraform_mounts.go
- proxmox/Internal/resource/guest/lxc/rootmount/schema.go
- proxmox/Internal/resource/guest/lxc/rootmount/sdk.go
- proxmox/Internal/resource/guest/lxc/rootmount/terraform.go
- proxmox/resource_lxc_new.go
Adds mount points to the new LXC implementation.
> Feat: LXC mounts

- proxmox/Internal/resource/guest/lxc/_sub/acl/schema.go
- proxmox/Internal/resource/guest/lxc/features/schema.go
- proxmox/Internal/resource/guest/lxc/features/sdk.go
- proxmox/Internal/resource/guest/lxc/features/terraform.go
- proxmox/Internal/resource/guest/lxc/mounts/sdk_mount.go
- proxmox/Internal/resource/guest/lxc/mounts/terraform_mount.go
- proxmox/resource_lxc_new.go
Adds support for LXC features.
Noticed some diffing issues with LXC `mount` during testing and fixed the issues I discovered.
> Feat: Lxc features

- docs/resources/vm_qemu.md
- proxmox/Internal/resource/guest/vmid/schema.go
> feat: can't set `vmid` to 0
